### ISSUE TITLE
FileNotFoundException when running on Windows

### ISSUE THREAD

**Issue by transcend3nt** [ChrisMcMStone/spinner#1]
After compiling and executing on Windows 7, JDK 1.8, it seems that the application was trying to create a log file but there was an exception:

java -cp ".;libs/*" Launcher -c config -w whitelist

Writing log to: log-2017-12-08T15:52:40.632
Exception in thread "main" java.io.FileNotFoundException: log-2017-12-08T15:52:40.632 (The filename, directory name, or
volume label syntax is incorrect)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileWriter.<init>(Unknown Source)
        at Launcher.main(Launcher.java:69)

**Comment by transcend3nt** [comment]
By specifying a custom log file name would work:

java -cp ".;libs/*" Launcher -c config -w whitelist -l log.txt
